### ISSUE TITLE
error on initial run

### ISSUE THREAD

**Issue by bentito** [dmirij/DataCodes#1]
I am running script and I get the following error:

```bash
> # extract monthly average temperature for baseline ------------------------
> months_vector  <- (yerevan_berkeley[51, 1] %>% 
+   str_split("    "))[[1]][2:13] %>% 
+   trimws(which = "both", whitespace = "[ \t\r\n]")
Error in stri_split_regex(string, pattern, n = n, simplify = simplify,  : 
  object 'yerevan_berkeley' not found
```

**Comment by dmirij** [comment]
Hi bentito, 
What you are experiencing is most likely a path problem.  The code did not read in the file, and the path to the file locally may not be right.  Try running getwd() in R and see if the path you are using is correct.

**Comment by bentito** [comment]
Yeah I think so, works well now! See:
<img width="1377" alt="image" src="https://user-images.githubusercontent.com/4449199/128058946-a6d3ca6b-4f94-4d98-a9ec-fac578c22aba.png">
